### ISSUE TITLE
Tailwind JIT does not seem to work quite right

### ISSUE THREAD

**Issue by ethan-tqa** [srmullen/sttv#4]
I would like to use TailwindCSS JIT for all the benefit it brings, but the issue is that changes are not updated with hot reload, I need to manually refresh the page. The steps I used to enable JIT mode:

- Add TAILWIND_MODE=watch to the dev command
- Add mode: 'jit' to tailwind config

Did I miss out anything?

**Comment by srmullen** [comment]
If you can get JIT mode to work you're welcome to make a pull request. I was looking at it when I made this library but couldn't get it working at the time. For now, I'm going to wait until that feature is out of preview.
